development:
  adapter: postgresql
  database: numerology_development
  pool: 5
  host: localhost
  username: danielberryman
  password: 
  url: <%= ENV['DATABASE_URL'] %>
    
test:
  adapter: postgresql
  database: numerology_test
  pool: 5
  host: localhost
  username: danielberryman
  password: 